Repository zitadel/zitadel-charts, pull requests merged in 2022-07, with the labels that each got.

#19 docs: fix example domain
  README.md
Labels: bug, documentation

#21 Developer focus
  README.md
  charts/zitadel/templates/configmap.yaml
  charts/zitadel/test/integration/accessibility.go
  charts/zitadel/test/integration/after.go
  charts/zitadel/test/integration/availability.go
  charts/zitadel/test/integration/before.go
  charts/zitadel/test/integration/e2e_test.go
  charts/zitadel/test/integration/integration_test.go
  charts/zitadel/test/integration/listening.go
  charts/zitadel/test/integration/setup.go
  charts/zitadel/test/integration/wait.go
  go.mod
  go.sum
Labels: enhancement

#18 Add appProtocol to service
  charts/zitadel/Chart.yaml
  charts/zitadel/templates/deployment.yaml
  charts/zitadel/templates/service.yaml
  charts/zitadel/test/integration/listening.go
  charts/zitadel/values.yaml
Labels: enhancement

#27 link to docs
  README.md
Labels: documentation
