Repository zitadel/zitadel-charts, pull requests merged in 2022-12, with the labels that each got.

#50 fix: enable and describe proper cleanup
  README.md
  charts/zitadel/Chart.yaml
  charts/zitadel/templates/configmap.yaml
  charts/zitadel/templates/secret_db-ssl-root-crt.yaml
  charts/zitadel/templates/secret_zitadel-masterkey.yaml
  charts/zitadel/templates/secret_zitadel-secrets.yaml
Labels: bug, documentation

#49 feat: add firstinstance handling
  README.md
  charts/zitadel/Chart.yaml
  charts/zitadel/templates/NOTES.txt
  charts/zitadel/templates/_helpers.tpl
  charts/zitadel/templates/rbac.yaml
  charts/zitadel/templates/setupjob.yaml
  charts/zitadel/values.yaml
Labels: enhancement

#55 fix: configurable key writer image
  charts/zitadel/Chart.yaml
  charts/zitadel/templates/_helpers.tpl
  charts/zitadel/templates/setupjob.yaml
  charts/zitadel/values.yaml
Labels: bug
